### ISSUE TITLE
Exception - TypeError: object is not callable

### ISSUE THREAD

**Issue by kekukui** [vlmaksime/weather.gismeteo#1]
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.TypeError'>
 Error Contents: 'NoneType' object is not callable
 Traceback (most recent call last):
 File "/storage/.kodi/addons/weather.gismeteo/default.py", line 699, in <module>
weather.run()
File "/storage/.kodi/addons/weather.gismeteo/resources/lib/simpleweather.py", line 51, in run
 self._resolve_function()
File "/storage/.kodi/addons/weather.gismeteo/resources/lib/simpleplugin.py", line 1020, in _resolve_function
return action_callable(self._params)
 File "/storage/.kodi/addons/weather.gismeteo/default.py", line 593, in forecast
 location_name, location_id = get_location(params.id)
File "/storage/.kodi/addons/weather.gismeteo/default.py", line 654, in get_location
 location = gismeteo.cities_ip()
 File "/storage/.kodi/addons/weather.gismeteo/resources/lib/gismeteo.py", line 313, in cities_ip
 for location in locations:
File "/storage/.kodi/addons/weather.gismeteo/resources/lib/gismeteo.py", line 135, in _get_locations_list
 root = etree.fromstring(xml)
 File "<string>", line 123, in XML
TypeError: 'NoneType' object is not callable
-->End of Python script error report<--
```

**Comment by vlmaksime** [comment]
Looks like a problem in the ElementTree library. Can You upload full log using add-on [Kodi Logfile Uploader](https://kodi.tv/addon/program-add-ons-scripts/kodi-logfile-uploader)?

**Comment by kekukui** [comment]
I can not reproduce the error at this time, the problem is intermittent.  I will update this issue when I have more information.
