### ISSUE TITLE
Gismetro stopped working in Kodi Nexus Skin Esturary - No Weather Preview

### ISSUE THREAD

**Issue by bassemolufda** [vlmaksime/weather.gismeteo#28]
![Screenshot_20231203-083315](https://github.com/vlmaksime/weather.gismeteo/assets/21076338/f5bc76ee-d7e4-4f3c-b6fe-c975ad1e1801)
![Screenshot_20231203-085104](https://github.com/vlmaksime/weather.gismeteo/assets/21076338/619cd845-a951-40a6-91c8-1fa21131c423)
![Screenshot_20231203-155317](https://github.com/vlmaksime/weather.gismeteo/assets/21076338/69d79903-9551-4ad1-8a23-37751f61e4b7)
![Screenshot_20231203-155340](https://github.com/vlmaksime/weather.gismeteo/assets/21076338/206f16af-0d99-4132-8c1b-eca0dd9b06da)

Gismeteo does not more working in Skin Estuary. Fresh install on Raspberry PI 4  with Arch-Linux and on Kodi on Amazon Fire Tablet 10.

Kodi Version 20.2 (20.2.0) GIT 20230629
Gismeteo 0.6.4+matrix.1

**Comment by DogfrosterBN** [comment]
same here, no weather with version 0.6.4 in Skin Estuary  Libreelec 11.0.3  Kodi 20.2 Nexus

**Comment by vigilant4u** [comment]
same here, Fresh install & no weather forecast and no weather location switch possible with with version 0.6.4 in Skin Estuary on Kodi 20.2 Nexus. Sad but tue

**Comment by myxor** [comment]
Maybe this is the reason:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'p'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.module.simpleplugin3/libs/simpleplugin.py", line 795, in _get_cached_data
                                                       data, timestamp = cache[key]
                                                     File "/home/osmc/.kodi/addons/script.module.simpleplugin3/libs/simpleplugin.py", line 381, in __getitem__
                                                       raise KeyError(key)
                                                   KeyError: "_location_forecast('de', '[redacted location id]'){}"
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/default.py", line 498, in <module>
                                                       weather.run()
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/resources/libs/simpleweather/simpleweather.py", line 475, in run
                                                       self._resolve_function()
                                                     File "/home/osmc/.kodi/addons/script.module.simpleplugin3/libs/simpleplugin.py", line 1128, in _resolve_function
                                                       return action_callable(self._params)
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/default.py", line 364, in forecast
                                                       data = _location_forecast(lang, location.id)
                                                     File "/home/osmc/.kodi/addons/script.module.simpleplugin3/libs/simpleplugin.py", line 850, in inner_wrapper
                                                       return self._get_cached_data(cache, func, duration,
                                                     File "/home/osmc/.kodi/addons/script.module.simpleplugin3/libs/simpleplugin.py", line 801, in _get_cached_data
                                                       data = func(*args, **kwargs)
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/default.py", line 415, in _location_forecast
                                                       return _call_method(gismeteo.forecast, params)
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/default.py", line 472, in _call_method
                                                       return func(**params)
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/resources/libs/gismeteo.py", line 263, in forecast
                                                       return self._get_forecast_info(x)
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/resources/libs/gismeteo.py", line 107, in _get_forecast_info
                                                       'days': self._get_days_forecast(xml_location),
                                                     File "/home/osmc/.kodi/addons/weather.gismeteo/resources/libs/gismeteo.py", line 174, in _get_days_forecast
                                                       'avg': self._get_int(xml_day.attrib['p']),
                                                   KeyError: 'p'
                                                   -->End of Python script error report<--

```
